#SPDX-License-Identifier: MIT-0
---
# tasks file for packages
- name: install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - net-tools
    - dnsutils
    - wget
    - curl
    - mc
    - rsync
