---
all:
  hosts:
    linux:
      ansible_host: 158.160.63.192
  vars:
    ansible_ssh_private_key_file: ~/.ssh/sysadm_practicum
    ansible_user: user
    ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
  children:
    nginx:
      hosts:
        linux-proxy-nginx:
          ansible_host: 158.160.105.220
        linux-nginx:
          ansible_host: 84.201.128.233
      vars:
        ansible_ssh_private_key_file: ~/.ssh/sysadm_practicum
        ansible_user: user
        ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
